### ISSUE TITLE
lfmerge fails to install on Ubuntu 16.10

### ISSUE THREAD

**Issue by jecompton** [sillsdev/web-cat#1]
Hi Palaso people,

I used to be in Sentani, and attended an IT conference about 4 years ago. We had to leave to be close to my parents, but maybe I can write some tests/refactor/put in bugfixes now and then.

I always run the latest Ubuntu. I'm sure you target LTS versions (as you should), but I'm happy to provide fixes I find (I already put in a pull request for the ops-devbox repo to bring it up-to-date).

I'll trace through the dependencies and fix it myself if I can, but since it is LF-specific I thought I'd ask here first since info might be scarce via usual DuckDuckGo search.

Here's the error I got:

failed: [localhost] (item=[u'lfmerge']) => {"failed": true, "item": ["lfmerge"], "msg": "No package matching 'lfmerge' is available"}

**Comment by jecompton** [comment]
Umm... yeah, is there a ppa I'm missing?

**Comment by darcywong00** [comment]
Hi there,

Sorry for the late response.  Next week, you can contact our software manager @megahirt for ways to contribute to Language Forge.

I'm closing this issue for two reasons:
- Language Forge and its issues go in the [**web-languageforge**](https://github.com/sillsdev/web-languageforge) repo.  I think this **web-cat** repo is intended for separate computer-assisted translation development.
- [**lfmerge**](https://github.com/sillsdev/LfMerge) is the server-side application that allows Language Forge to Send/Receive with Fieldworks projects.  Our resource constraints limit our development & packaging to LTS Trusty and Xenial.

**Comment by ddaspit** [comment]
@jecompton, you are not missing a PPA. The ansible script adds the correct apt repos, there just aren't any lfmerge packages for 16.10 in the repos. As @darcywong00 mentioned, we don't have the resources to support them right now.

**Comment by megahirt** [comment]
@jecompton, just wanted to say thanks for the open-source contributions, of
which we receive very little.  As you know we can't support anything else
than the LTS Ubuntu but feel free to check out language forge and lfmerge
on the LTS - your input on installation and running it could be valuable.
